global:
  scrape_interval: 10s

rule_files:
 - /etc/prometheus/alerts/*.yml

alerting:
 alertmanagers:
 - static_configs:
   - targets:
     - alertmanager:9093
#
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
#
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
#   Drop extra labels
    metric_relabel_configs:
      - regex: 'container_label_.*'
        action: labeldrop
#   Drop metrics
# TODO
#
  - job_name: 'sites'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
    - files:
      - 'file_sd/targets.json'
      refresh_interval: 5m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.
#
  - job_name: 'nodes'
    static_configs:
    file_sd_configs:
    - files:
      - 'file_sd/targets.json'
