{
 "title": "Uptime Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  { "title": "Senior Systems Sites Up", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sites Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(probe_success{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of sites up",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(probe_success{job=~\"$job\"})",
     "legendFormat": "Servers up"
    },
    {
     "expr": "sum(1-probe_success{job=~\"$job\"})",
     "legendFormat": "Servers down"
    }
   ]
  },
  {
   "title": "Sites Down",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(1-probe_success{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Instance status",
   "type": "table",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=~\"$job\"}[5m])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\"}[10m])*1000"
    }
   ]
  }
 ]
}