groups:
- name: uptime_alerts
  rules:
  #
  - alert: site_down_websites
    expr: probe_success{job="sites"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "DM site/service down."
      description: "{{ $labels.instance }} service is down."
